### ISSUE TITLE
download usa trade data

### ISSUE THREAD

**Issue by alexandersimoes** [observatory-economic-complexity/oec-etl#33]
The US data that I had ingested seemed to be cut off at a certain number of rows. Let's prioritize downloading the most recent months of 2019 and moving backwards from there with a file per month: all district / all prods / all destination countries.

**Comment by vbebo** [comment]
2019 State Export complete

**Comment by vbebo** [comment]
2019 State Import complete

**Comment by vbebo** [comment]
Still have Port, District (HS), and District (NAICS) to do

**Comment by davelandry** [comment]
we've decided not to do port data (too difficult to download everything)

**Comment by davelandry** [comment]
also no NAICS District

**Comment by vbebo** [comment]
2019 01-07 District Import complete. Next is District Export, State Import, and Export for July 2019

**Comment by vbebo** [comment]
2019 complete
