### ISSUE TITLE
download all canada trade data

### ISSUE THREAD

**Issue by alexandersimoes** [observatory-economic-complexity/oec-etl#36]
Data is monthly and subnational. Files:

2017 - 2019
https://open.canada.ca/data/en/dataset/b1126a07-fd85-4d56-8395-143aba1747a4
2012 - 2016
https://open.canada.ca/data/en/dataset/6f3fd3d9-5a35-47a8-a45a-4b2a8c957453
2007 - 2011
https://open.canada.ca/data/en/dataset/d0c43a70-3390-4879-8f1d-b602bb0eba3d
2002 - 2006
https://open.canada.ca/data/en/dataset/7b9ef472-e806-42f8-8e2a-c8d954e250e0
1996 - 2001
https://open.canada.ca/data/en/dataset/ed551c1b-ba5d-4391-a08e-8c154fb2e629
1992 - 1995
https://open.canada.ca/data/en/dataset/6eacb78a-7fb1-49ce-b13c-2a7564092a55
1988 - 1991
https://open.canada.ca/data/en/dataset/a2b38e8a-b0b0-4163-8426-c4729b0a9689

You may need to synch w/ @Jayrmajithia to determine the best format / renaming procedure with him but we'll want all these files.

**Comment by vbebo** [comment]
https://console.cloud.google.com/storage/browser/oec-raw-data/Canada/Trade?project=oec-staging&folder=true&organizationId=true&supportedpurview=project

Downloaded and Uploaded. I will partner with Jay to go over any changes

**Comment by vbebo** [comment]
Jay said the file names work as they are
